//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnChuyenNganh.Areas.Admin.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataAdminGearShop : DbContext
    {
        public DataAdminGearShop()
            : base("name=DataAdminGearShop")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<categorize> categorizes { get; set; }
        public virtual DbSet<color> colors { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customeraddress> customeraddresses { get; set; }
        public virtual DbSet<discount> discounts { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<image> images { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<orderdetail> orderdetails { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<position> positions { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<productdiscount> productdiscounts { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<@switch> switches { get; set; }
        public virtual DbSet<warehouse> warehouses { get; set; }
    }
}
