//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnChuyenNganh.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public string Product1 { get; set; }
        public string CategorizeID { get; set; }
        public string ProductDiscountID { get; set; }
        public string SupplierID { get; set; }
        public string DisplayName { get; set; }
        public Nullable<double> ImportPrice { get; set; }
        public Nullable<double> SellPrice { get; set; }
        public Nullable<int> NumberOfLike { get; set; }
        public Nullable<double> Ratting { get; set; }
        public Nullable<int> NumberOfRatting { get; set; }
        public string Material { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> Warranty { get; set; }
        public string ConnectionType { get; set; }
        public Nullable<int> ProgrammableButton { get; set; }
        public Nullable<double> Size { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string UpdateBy { get; set; }
        public bool Status { get; set; }
    }
}
