//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnChuyenNganh.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse
    {
        public string ColorID { get; set; }
        public string ProductID { get; set; }
        public string SwitchID { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
